import { useState } from 'react';
import axios from 'axios';
import { jsPDF } from 'jspdf';
import '../styles/ReportGenerator.css';

export default function ReportGenerator({ 
  result, 
  user, 
  selectedPatient, 
  diagnosticId, 
  signature,
  onReportGenerated 
}) {
  const [generating, setGenerating] = useState(false);
  const [language, setLanguage] = useState('fr');
  const [format, setFormat] = useState('pdf');

  const translations = {
    fr: {
      title: 'RAPPORT D\'ANALYSE PULMONAIRE - IA',
      patient: 'Patient',
      doctor: 'Médecin',
      date: 'Date',
      diagnosis: 'Diagnostic',
      confidence: 'Niveau de confiance',
      probabilities: 'Probabilités détaillées',
      cancer: 'Cancer',
      normal: 'Normal',
      riskLevel: 'Niveau de risque',
      description: 'DESCRIPTION CLINIQUE',
      recommendations: 'RECOMMANDATIONS MÉDICALES',
      signature: 'SIGNATURE DU MÉDECIN',
      signedBy: 'Signé par',
      warning: 'AVERTISSEMENT',
      warningText: "Ce rapport est généré par un système d'intelligence artificielle. Il ne remplace pas l'avis d'un professionnel de santé qualifié. Toute décision médicale doit être validée par un médecin.",
      footer: 'MediCare Diagnostics - Système d\'aide au diagnostic par IA'
    },
    en: {
      title: 'LUNG ANALYSIS REPORT - AI',
      patient: 'Patient',
      doctor: 'Doctor',
      date: 'Date',
      diagnosis: 'Diagnosis',
      confidence: 'Confidence level',
      probabilities: 'Detailed probabilities',
      cancer: 'Cancer',
      normal: 'Normal',
      riskLevel: 'Risk level',
      description: 'CLINICAL DESCRIPTION',
      recommendations: 'MEDICAL RECOMMENDATIONS',
      signature: 'DOCTOR\'S SIGNATURE',
      signedBy: 'Signed by',
      warning: 'WARNING',
      warningText: 'This report is generated by an artificial intelligence system. It does not replace the advice of a qualified healthcare professional. All medical decisions must be validated by a doctor.',
      footer: 'MediCare Diagnostics - AI-assisted diagnostic system'
    },
    ar: {
      title: 'تقرير تحليل الرئة - الذكاء الاصطناعي',
      patient: 'المريض',
      doctor: 'الطبيب',
      date: 'التاريخ',
      diagnosis: 'التشخيص',
      confidence: 'مستوى الثقة',
      probabilities: 'الاحتمالات التفصيلية',
      cancer: 'سرطان',
      normal: 'طبيعي',
      riskLevel: 'مستوى الخطر',
      description: 'الوصف السريري',
      recommendations: 'التوصيات الطبية',
      signature: 'توقيع الطبيب',
      signedBy: 'وقع من قبل',
      warning: 'تحذير',
      warningText: 'هذا التقرير تم إنشاؤه بواسطة نظام ذكاء اصطناعي. لا يحل محل رأي أخصائي رعاية صحية مؤهل. يجب التحقق من جميع القرارات الطبية من قبل طبيب.',
      footer: 'MediCare Diagnostics - نظام مساعدة التشخيص بالذكاء الاصطناعي'
    }
  };

  const t = translations[language];

  const getPatientName = () => {
    return user.role === 'medecin' 
      ? `${selectedPatient?.prenom || ''} ${selectedPatient?.nom || ''}`
      : `${user.prenom} ${user.nom}`;
  };

  const getDoctorName = () => {
    return user.role === 'medecin'
      ? `Dr. ${user.prenom} ${user.nom}`
      : (user.medecin_nom || 'Médecin non assigné');
  };

  const generateTXT = () => {
    const patientName = getPatientName();
    const doctorName = getDoctorName();
    const dateStr = new Date().toLocaleString(language === 'ar' ? 'ar-MA' : language === 'en' ? 'en-US' : 'fr-FR');

    const content = `
═══════════════════════════════════════════════════
         ${t.title}
═══════════════════════════════════════════════════

${t.patient}: ${patientName}
${t.date}: ${dateStr}
${t.doctor}: ${doctorName}

───────────────────────────────────────────────────
${t.diagnosis.toUpperCase()}
───────────────────────────────────────────────────

${t.diagnosis}: ${result.class}
${t.confidence}: ${result.confidence.toFixed(2)}%
${t.riskLevel}: ${result.risk_level}

${t.probabilities}:
  • ${t.cancer}: ${(result.probabilities.cancer * 100).toFixed(2)}%
  • ${t.normal}: ${(result.probabilities.normal * 100).toFixed(2)}%

───────────────────────────────────────────────────
${t.description}
───────────────────────────────────────────────────

${result.description}

───────────────────────────────────────────────────
${t.recommendations}
───────────────────────────────────────────────────

${result.recommendation}

${signature ? `
───────────────────────────────────────────────────
${t.signature}
───────────────────────────────────────────────────
${t.signedBy}: ${doctorName}
${t.date}: ${dateStr}
` : ''}

───────────────────────────────────────────────────
${t.warning}
───────────────────────────────────────────────────

${t.warningText}

═══════════════════════════════════════════════════
        ${t.footer}
═══════════════════════════════════════════════════
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Rapport_${patientName.replace(/\s/g, '_')}_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    if (onReportGenerated) {
      onReportGenerated({ success: true, format: 'txt' });
    }

    alert('✅ Rapport TXT téléchargé avec succès !');
  };

  const generatePDF = async () => {
    if (!result) {
      alert('❌ Aucun résultat à exporter');
      return;
    }

    setGenerating(true);

    try {
      const doc = new jsPDF();
      const patientName = getPatientName();
      const doctorName = getDoctorName();
      const dateStr = new Date().toLocaleString(language === 'ar' ? 'ar-MA' : language === 'en' ? 'en-US' : 'fr-FR');

      let yPos = 20;

      // Titre
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(t.title, 105, yPos, { align: 'center' });

      yPos += 15;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');

      // Patient
      doc.setFont('helvetica', 'bold');
      doc.text(`${t.patient}:`, 20, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(patientName, 60, yPos);

      yPos += 7;
      doc.setFont('helvetica', 'bold');
      doc.text(`${t.doctor}:`, 20, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(doctorName, 60, yPos);

      yPos += 7;
      doc.setFont('helvetica', 'bold');
      doc.text(`${t.date}:`, 20, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(dateStr, 60, yPos);

      // Diagnostic
      yPos += 15;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text(t.diagnosis.toUpperCase(), 20, yPos);

      yPos += 10;
      doc.setFontSize(16);
      doc.text(result.class, 20, yPos);

      yPos += 10;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`${t.confidence}: ${result.confidence.toFixed(2)}%`, 20, yPos);

      // Probabilités
      yPos += 12;
      doc.setFont('helvetica', 'bold');
      doc.text(`${t.probabilities}:`, 20, yPos);

      yPos += 7;
      doc.setFont('helvetica', 'normal');
      doc.text(`- ${t.cancer}: ${(result.probabilities.cancer * 100).toFixed(2)}%`, 25, yPos);

      yPos += 6;
      doc.text(`- ${t.normal}: ${(result.probabilities.normal * 100).toFixed(2)}%`, 25, yPos);

      yPos += 6;
      doc.text(`- ${t.riskLevel}: ${result.risk_level}`, 25, yPos);

      // Description
      yPos += 12;
      doc.setFont('helvetica', 'bold');
      doc.text(t.description, 20, yPos);

      yPos += 7;
      doc.setFont('helvetica', 'normal');
      const descLines = doc.splitTextToSize(result.description, 170);
      doc.text(descLines, 20, yPos);
      yPos += descLines.length * 6;

      // Recommandations
      yPos += 10;
      doc.setFont('helvetica', 'bold');
      doc.text(t.recommendations, 20, yPos);

      yPos += 7;
      doc.setFont('helvetica', 'normal');
      const recoLines = doc.splitTextToSize(result.recommendation, 170);
      doc.text(recoLines, 20, yPos);
      yPos += recoLines.length * 6;

      // Signature
      if (signature) {
        yPos += 15;
        doc.setFont('helvetica', 'bold');
        doc.text(t.signature, 20, yPos);

        yPos += 5;
        try {
          doc.addImage(signature, 'PNG', 20, yPos, 60, 30);
          yPos += 35;
        } catch (e) {
          console.error('Erreur ajout signature:', e);
          yPos += 10;
        }

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.text(`${t.signedBy}: ${doctorName}`, 20, yPos);
        yPos += 5;
        doc.text(`${t.date}: ${dateStr}`, 20, yPos);
      }

      // Avertissement
      yPos += 15;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(t.warning, 20, yPos);

      yPos += 6;
      doc.setFont('helvetica', 'normal');
      const warningLines = doc.splitTextToSize(t.warningText, 170);
      doc.text(warningLines, 20, yPos);

      // Pied de page
      doc.setFontSize(8);
      doc.text(t.footer, 105, 285, { align: 'center' });

      // Télécharger
      const fileName = `Rapport_${patientName.replace(/\s/g, '_')}_${Date.now()}.pdf`;
      doc.save(fileName);

      if (onReportGenerated) {
        onReportGenerated({ success: true, fileName });
      }

      alert('✅ Rapport PDF téléchargé avec succès !');

    } catch (error) {
      console.error('❌ Erreur génération PDF:', error);
      alert('❌ Erreur lors de la génération du PDF');
    } finally {
      setGenerating(false);
    }
  };

  const handleGenerate = () => {
    setGenerating(true);
    try {
      if (format === 'txt') {
        generateTXT();
      } else {
        generatePDF();
      }
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="report-generator">
      <div className="report-header">
        <div className="report-icon">📄</div>
        <div className="report-info">
          <h3>Rapport Médical Personnalisé</h3>
          <p>Choisissez la langue et le format du rapport</p>
        </div>
      </div>

      <div className="report-options">
        <div className="option-group">
          <label>🌍 Langue</label>
          <select value={language} onChange={(e) => setLanguage(e.target.value)}>
            <option value="fr">🇫🇷 Français</option>
            <option value="en">🇬🇧 English</option>
            <option value="ar">🇲🇦 العربية</option>
          </select>
        </div>

        <div className="option-group">
          <label>📑 Format</label>
          <select value={format} onChange={(e) => setFormat(e.target.value)}>
            <option value="pdf">📕 PDF</option>
            <option value="txt">📄 TXT</option>
          </select>
        </div>
      </div>

      <div className="report-details">
        <div className="report-detail-item">
          <span className="detail-icon">👤</span>
          <div>
            <strong>Patient</strong>
            <p>{getPatientName()}</p>
          </div>
        </div>

        <div className="report-detail-item">
          <span className="detail-icon">👨‍⚕️</span>
          <div>
            <strong>Médecin</strong>
            <p>{getDoctorName()}</p>
          </div>
        </div>

        <div className="report-detail-item">
          <span className="detail-icon">📋</span>
          <div>
            <strong>Diagnostic</strong>
            <p className={`diagnosis-badge ${result?.color}`}>
              {result?.class || 'N/A'}
            </p>
          </div>
        </div>

        {signature && (
          <div className="report-detail-item">
            <span className="detail-icon">✅</span>
            <div>
              <strong>Statut</strong>
              <p style={{ color: '#10b981', fontWeight: 600 }}>
                Signé électroniquement
              </p>
            </div>
          </div>
        )}
      </div>

      <button
        onClick={handleGenerate}
        disabled={generating || !result}
        className="btn-download-pdf"
      >
        {generating ? (
          <>
            <span className="spinner-small"></span>
            Génération en cours...
          </>
        ) : (
          <>
            📥 Télécharger le Rapport {format.toUpperCase()}
          </>
        )}
      </button>

      {!signature && user.role === 'medecin' && (
        <p className="report-warning">
          💡 <strong>Astuce :</strong> Ajoutez votre signature électronique avant de générer le rapport final
        </p>
      )}
    </div>
  );
}